"""
Notes Parser - Extract structured data from Plaud notes.md files.

Parses action items, decisions, key discussion points, and follow-ups
from the markdown notes generated by Plaud AI.
"""

import re
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import List, Optional
from datetime import datetime
import json
import logging

logger = logging.getLogger(__name__)

PLAUD_EXPORT_DIR = Path(__file__).parent.parent.parent / "data" / "plaud_transcripts"


@dataclass
class ActionItem:
    description: str
    owner: str = "Unassigned"
    due_date: str = ""
    status: str = "open"  # open | completed
    source_meeting: str = ""
    source_file_id: str = ""
    meeting_date: str = ""


@dataclass
class Decision:
    description: str
    rationale: str = ""
    source_meeting: str = ""
    source_file_id: str = ""
    meeting_date: str = ""


@dataclass
class ParsedNotes:
    summary: str = ""
    keywords: List[str] = field(default_factory=list)
    participants: List[str] = field(default_factory=list)
    meeting_date: str = ""
    key_points: List[str] = field(default_factory=list)
    action_items: List[ActionItem] = field(default_factory=list)
    decisions: List[Decision] = field(default_factory=list)
    follow_ups: List[str] = field(default_factory=list)

    def to_dict(self):
        d = asdict(self)
        return d


def parse_notes(content: str, meeting_title: str = "", file_id: str = "", meeting_date: str = "") -> ParsedNotes:
    """Parse a notes.md file content into structured data."""
    result = ParsedNotes()
    result.meeting_date = meeting_date

    if not content or len(content.strip()) < 50:
        result.summary = content.strip()
        return result

    # Extract keywords
    kw_match = re.search(r'Keywords\s*\n(.*?)(?:\n\n|\n##)', content, re.DOTALL)
    if kw_match:
        result.keywords = [k.strip().strip('`') for k in re.findall(r'`([^`]+)`', kw_match.group(1))]
    else:
        # Try inline keywords at top
        for line in content.split('\n')[:10]:
            backtick_kws = re.findall(r'`([^`]+)`', line)
            if backtick_kws and not line.startswith('#'):
                result.keywords.extend(backtick_kws)

    # Extract participants
    participants_match = re.search(r'Participants:\s*(.+)', content)
    if participants_match:
        raw = participants_match.group(1)
        result.participants = [p.strip().strip('[]') for p in re.split(r'\]\s*\[', raw)]

    # Extract summary / overview
    # Look for the first ## Meeting Notes or ## Theme or first substantive section
    summary_patterns = [
        r'## (?:📝\s*)?Meeting Notes\s*\n(.*?)(?=\n## (?:📅|💡|---)|$)',
        r'## Theme\s*\n(.*?)(?=\n## |$)',
        r'## Takeaways\s*\n(.*?)(?=\n## |$)',
        r'# Summary\s*\n(.*?)(?=\n# Meeting Minutes|\n---\n# Reasoning)',
    ]
    for pat in summary_patterns:
        m = re.search(pat, content, re.DOTALL)
        if m:
            result.summary = m.group(1).strip()
            break
    if not result.summary:
        # Fallback: first paragraph after any heading
        lines = content.strip().split('\n')
        text_lines = []
        started = False
        for line in lines:
            if line.startswith('#'):
                if started:
                    break
                started = True
                continue
            if started and line.strip():
                text_lines.append(line.strip())
        result.summary = '\n'.join(text_lines[:10])

    # Extract key discussion points from ### headings under Meeting Notes
    for m in re.finditer(r'### (.+?)\n(.*?)(?=\n### |\n## |\n---|\Z)', content, re.DOTALL):
        heading = m.group(1).strip()
        body = m.group(2).strip()
        # Get the first "Discussion Summary" or first bullet
        summary_m = re.search(r'\*\*Discussion Summary\*\*\s*\n(.*?)(?=\n- \*\*|\n###|\n##|\Z)', body, re.DOTALL)
        if summary_m:
            point_text = f"**{heading}**: {_clean_bullets(summary_m.group(1))}"
        else:
            first_bullets = []
            for line in body.split('\n'):
                stripped = line.strip()
                if stripped.startswith('- ') and not stripped.startswith('- **'):
                    first_bullets.append(stripped[2:].strip())
                if len(first_bullets) >= 2:
                    break
            point_text = f"**{heading}**: {'; '.join(first_bullets)}" if first_bullets else heading
        result.key_points.append(point_text)

    # Extract action items from multiple patterns
    _extract_action_items(content, result, meeting_title, file_id, meeting_date)

    # Extract decisions
    _extract_decisions(content, result, meeting_title, file_id, meeting_date)

    # Extract follow-ups from "Next Arrangements" or "Follow-up" sections
    followup_match = re.search(
        r'## (?:📅\s*)?(?:Next Arrangements|Follow-up Items?|Follow Up)\s*\n(.*?)(?=\n## |\n---|\Z)',
        content, re.DOTALL
    )
    if followup_match:
        for line in followup_match.group(1).split('\n'):
            stripped = line.strip()
            if stripped.startswith('- '):
                item = re.sub(r'^- \[.\]\s*', '', stripped).strip()
                if item:
                    result.follow_ups.append(item)

    return result


def _clean_bullets(text: str) -> str:
    """Clean bullet point text into a short summary."""
    lines = []
    for line in text.strip().split('\n'):
        stripped = line.strip()
        if stripped.startswith('- '):
            lines.append(stripped[2:].strip())
    return '; '.join(lines[:3]) if lines else text.strip()[:200]


def _extract_action_items(content: str, result: ParsedNotes, title: str, file_id: str, date: str):
    """Extract action items from various patterns in the notes."""
    seen = set()

    # Pattern 1: "- [ ] description" or "- [x] description"
    for m in re.finditer(r'- \[([ xX])\]\s*(.+)', content):
        status = "completed" if m.group(1).lower() == 'x' else "open"
        desc = m.group(2).strip()
        # Remove trailing "- [TBD]" or "- [date]"
        desc = re.sub(r'\s*-\s*\[.*?\]\s*$', '', desc).strip()
        if desc and desc.lower() not in seen:
            seen.add(desc.lower())
            # Try to extract owner from @Speaker pattern
            owner_m = re.match(r'@(\S+(?:\s+\d+)?)\s*[-:]\s*(.*)', desc)
            if owner_m:
                owner = owner_m.group(1).strip()
                desc = owner_m.group(2).strip()
            else:
                owner = "Unassigned"
            result.action_items.append(ActionItem(
                description=desc, owner=owner, status=status,
                source_meeting=title, source_file_id=file_id, meeting_date=date,
            ))

    # Pattern 2: "Action Item: @Speaker - task - due date" in meeting minutes
    for m in re.finditer(r'- Action Item:\s*@(\S+(?:\s+\d+)?)\s*-\s*(.*?)(?:\s*-\s*(No due date.*?|Due:.*?))?$',
                         content, re.MULTILINE):
        owner = m.group(1).strip()
        desc = m.group(2).strip()
        due = m.group(3).strip() if m.group(3) else ""
        if desc and desc.lower() not in seen:
            seen.add(desc.lower())
            result.action_items.append(ActionItem(
                description=desc, owner=owner, due_date=due, status="open",
                source_meeting=title, source_file_id=file_id, meeting_date=date,
            ))

    # Pattern 3: Lines starting with "@Speaker" in Action Items section
    ai_section = re.search(
        r'(?:^|\n)Action Items\s*\n(.*?)(?=\n(?:Key Decisions|Detailed Minutes|---|\Z))',
        content, re.DOTALL
    )
    if ai_section:
        for line in ai_section.group(1).split('\n'):
            stripped = line.strip()
            am = re.match(r'-?\s*@(\S+(?:\s+\d+)?)\s*-\s*(.*?)(?:\s*-\s*(No due date.*?|Due:.*?))?$', stripped)
            if am:
                owner = am.group(1).strip()
                desc = am.group(2).strip()
                due = am.group(3).strip() if am.group(3) else ""
                if desc and desc.lower() not in seen:
                    seen.add(desc.lower())
                    result.action_items.append(ActionItem(
                        description=desc, owner=owner, due_date=due, status="open",
                        source_meeting=title, source_file_id=file_id, meeting_date=date,
                    ))


def _extract_decisions(content: str, result: ParsedNotes, title: str, file_id: str, date: str):
    """Extract decisions from the notes."""
    seen = set()

    # Pattern 1: "Key Decision:" lines in meeting minutes
    for m in re.finditer(r'- Key Decision:\s*(.*?)(?:\s*-\s*Rationale:\s*(.*?))?$', content, re.MULTILINE):
        desc = m.group(1).strip()
        rationale = m.group(2).strip() if m.group(2) else ""
        if desc and desc.lower() not in seen:
            seen.add(desc.lower())
            result.decisions.append(Decision(
                description=desc, rationale=rationale,
                source_meeting=title, source_file_id=file_id, meeting_date=date,
            ))

    # Pattern 2: "Key Decisions" section in meeting minutes
    kd_section = re.search(
        r'(?:^|\n)Key Decisions\s*\n(.*?)(?=\nDetailed Minutes|\n---|\n#|\Z)',
        content, re.DOTALL
    )
    if kd_section:
        for line in kd_section.group(1).split('\n'):
            stripped = line.strip()
            if stripped.startswith('- ') and stripped[2:].strip():
                parts = stripped[2:].split(' - Rationale: ')
                desc = parts[0].strip()
                rationale = parts[1].strip() if len(parts) > 1 else ""
                if desc and desc.lower() not in seen:
                    seen.add(desc.lower())
                    result.decisions.append(Decision(
                        description=desc, rationale=rationale,
                        source_meeting=title, source_file_id=file_id, meeting_date=date,
                    ))

    # Pattern 3: "**Conclusion**" blocks
    for m in re.finditer(r'\*\*Conclusion\*\*\s*\n\s*-\s*(.*?)(?:\n\n|\n###|\n##|\Z)', content, re.DOTALL):
        desc = m.group(1).strip()
        if desc and len(desc) > 15 and desc.lower() not in seen:
            seen.add(desc.lower())
            result.decisions.append(Decision(
                description=desc, rationale="",
                source_meeting=title, source_file_id=file_id, meeting_date=date,
            ))


def load_all_transcripts_metadata():
    """Load metadata for all transcripts. Returns list of dicts."""
    if not PLAUD_EXPORT_DIR.exists():
        return []

    transcripts = []
    for tdir in sorted(PLAUD_EXPORT_DIR.iterdir()):
        if not tdir.is_dir():
            continue
        meta_path = tdir / "metadata.json"
        if not meta_path.exists():
            continue
        try:
            with open(meta_path) as f:
                meta = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue

        start_time = meta.get("start_time", 0)
        if start_time:
            date_str = datetime.fromtimestamp(start_time / 1000).strftime("%Y-%m-%d %H:%M")
            date_only = datetime.fromtimestamp(start_time / 1000).strftime("%Y-%m-%d")
        else:
            date_str = ""
            date_only = ""

        transcripts.append({
            "file_id": meta.get("file_id", ""),
            "title": meta.get("filename", tdir.name),
            "date": date_str,
            "date_only": date_only,
            "start_time": start_time,
            "duration_ms": meta.get("duration_ms", 0),
            "dir_name": tdir.name,
            "dir_path": str(tdir),
            "has_notes": (tdir / "notes.md").exists(),
            "has_transcript": (tdir / "transcript.json").exists(),
        })

    transcripts.sort(key=lambda x: x["start_time"], reverse=True)
    return transcripts


def get_parsed_notes_for_transcript(dir_path: str, title: str = "", file_id: str = "", meeting_date: str = "") -> Optional[ParsedNotes]:
    """Parse notes.md for a specific transcript directory."""
    notes_path = Path(dir_path) / "notes.md"
    if not notes_path.exists():
        return None
    content = notes_path.read_text()
    return parse_notes(content, meeting_title=title, file_id=file_id, meeting_date=meeting_date)


def get_all_action_items(
    status_filter: str = "",
    owner_filter: str = "",
    start_date: str = "",
    end_date: str = "",
) -> List[dict]:
    """Aggregate action items across all transcripts."""
    all_items = []
    for t in load_all_transcripts_metadata():
        if not t["has_notes"]:
            continue
        if start_date and t["date_only"] < start_date:
            continue
        if end_date and t["date_only"] > end_date:
            continue

        parsed = get_parsed_notes_for_transcript(
            t["dir_path"], title=t["title"],
            file_id=t["file_id"], meeting_date=t["date_only"]
        )
        if not parsed:
            continue

        for item in parsed.action_items:
            if status_filter and item.status != status_filter:
                continue
            if owner_filter and owner_filter.lower() not in item.owner.lower():
                continue
            all_items.append(asdict(item))

    return all_items


def get_all_decisions(
    start_date: str = "",
    end_date: str = "",
    keyword: str = "",
) -> List[dict]:
    """Aggregate decisions across all transcripts."""
    all_decisions = []
    for t in load_all_transcripts_metadata():
        if not t["has_notes"]:
            continue
        if start_date and t["date_only"] < start_date:
            continue
        if end_date and t["date_only"] > end_date:
            continue

        parsed = get_parsed_notes_for_transcript(
            t["dir_path"], title=t["title"],
            file_id=t["file_id"], meeting_date=t["date_only"]
        )
        if not parsed:
            continue

        for dec in parsed.decisions:
            if keyword and keyword.lower() not in dec.description.lower():
                continue
            all_decisions.append(asdict(dec))

    return all_decisions


def get_meeting_briefing(attendee_names: List[str], include_notes_snippets: bool = False) -> dict:
    """
    Given attendee names, find past meetings involving those people
    and return unresolved action items + key decisions.

    Args:
        attendee_names: List of attendee name strings to match.
        include_notes_snippets: If True, include first ~500 chars of notes
            content for each matching meeting (used by context synthesizer).
    """
    matching_meetings = []
    unresolved_items = []
    key_decisions = []

    name_patterns = [n.lower() for n in attendee_names if n]

    for t in load_all_transcripts_metadata():
        if not t["has_notes"]:
            continue

        # Check if any attendee name appears in title or notes
        title_lower = t["title"].lower()
        notes_path = Path(t["dir_path"]) / "notes.md"
        notes_content = ""
        if notes_path.exists():
            notes_content = notes_path.read_text()

        match = any(
            name in title_lower or name in notes_content.lower()
            for name in name_patterns
        )
        if not match:
            continue

        meeting_entry = {
            "title": t["title"],
            "date": t["date"],
            "file_id": t["file_id"],
        }
        if include_notes_snippets and notes_content:
            meeting_entry["notes_snippet"] = notes_content[:500]

        matching_meetings.append(meeting_entry)

        parsed = get_parsed_notes_for_transcript(
            t["dir_path"], title=t["title"],
            file_id=t["file_id"], meeting_date=t["date_only"]
        )
        if not parsed:
            continue

        for item in parsed.action_items:
            if item.status == "open":
                unresolved_items.append(asdict(item))

        for dec in parsed.decisions:
            key_decisions.append(asdict(dec))

    return {
        "attendees": attendee_names,
        "matching_meetings": matching_meetings[:20],
        "total_past_meetings": len(matching_meetings),
        "unresolved_action_items": unresolved_items[:30],
        "key_decisions": key_decisions[:20],
    }
