#!/bin/bash
# Daily Digest Generator
# Compiles weather, tasks, and other info into a digest

echo "📋 DAILY DIGEST - $(date '+%A, %B %d, %Y')"
echo "==========================================="
echo ""

# Weather (using wttr.in)
echo "🌤️ WEATHER - Dallas, TX"
echo "------------------------"
curl -s "wttr.in/Dallas,TX?format=3" 2>/dev/null || echo "Weather unavailable"
curl -s "wttr.in/Dallas,TX?format=%t+%C+%w" 2>/dev/null || echo ""
echo ""

# To-Do Summary
echo "📝 TO-DO PRIORITIES"
echo "-------------------"
if [ -f /home/ubuntu/clawd/memory/arvind-todo-jan28.md ]; then
    grep -E "^\- \[ \]" /home/ubuntu/clawd/memory/arvind-todo-jan28.md | head -5
else
    echo "No to-do file found"
fi
echo ""

# Flight Status
echo "✈️ FLIGHT TRACKING"
echo "------------------"
if [ -f /home/ubuntu/clawd/memory/flight-tracking.json ]; then
    echo "Outbound (DFW→DEL ~Feb 9): \$$(jq -r '.lowest_seen.outbound' /home/ubuntu/clawd/memory/flight-tracking.json)"
    echo "Return (DEL→DFW Feb 25): \$$(jq -r '.lowest_seen.return' /home/ubuntu/clawd/memory/flight-tracking.json)"
fi
echo ""

# Recent Journal Entry
echo "📓 YESTERDAY'S HIGHLIGHTS"
echo "-------------------------"
YESTERDAY=$(date -d "yesterday" '+%Y-%m-%d' 2>/dev/null || date -v-1d '+%Y-%m-%d')
if [ -f "/home/ubuntu/clawd/second-brain/journal/${YESTERDAY}.md" ]; then
    head -20 "/home/ubuntu/clawd/second-brain/journal/${YESTERDAY}.md" | grep -v "^#" | head -5
else
    echo "No journal entry for yesterday"
fi
echo ""

echo "==========================================="
echo "Generated by Nike 🐾 at $(date '+%H:%M %Z')"
