#!/bin/bash
# Email Digest - Summarizes recent unread emails
# Uses himalaya CLI

echo "📧 EMAIL DIGEST - $(date '+%Y-%m-%d %H:%M')"
echo "==========================================="
echo ""

# Check for important emails from work account
echo "📥 RECENT EMAILS (Work)"
echo "-----------------------"
himalaya envelope list -a work -f INBOX 2>/dev/null | grep -v "WARN\|Info" | head -15

echo ""
echo "📌 IMPORTANT SENDERS TO WATCH:"
echo "  - Yugal Kapoor"
echo "  - Vivin Ramamoorthy"  
echo "  - Michael McGowan"
echo "  - Manas Mallik"
echo ""

# Count unread
UNREAD=$(himalaya envelope list -a work -f INBOX 2>/dev/null | grep " \* " | wc -l)
echo "📊 Unread count: ~$UNREAD"
echo ""
echo "==========================================="
echo "Generated by Nike 🐾"
